#!/usr/bin/env bash
#
# punch/gen-shadowrocket-config.sh — Generate a Shadowrocket .conf file
# from one or two deploy-output.txt files.
#
# Usage:
#   ./gen-shadowrocket-config.sh <deploy-output.txt>
#   ./gen-shadowrocket-config.sh <work-output.txt> <video-output.txt>
#
# Run locally on your Mac. Produces shadowrocket.conf in the current directory.
# Import into Shadowrocket on iOS via file sharing / AirDrop / iCloud.
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC}  $*"; }
error() {
  echo -e "${RED}[ERROR]${NC} $*"
  exit 1
}

if [[ $# -eq 1 ]]; then
  MODE="single"
elif [[ $# -eq 2 ]]; then
  MODE="dual"
else
  error "Usage: $0 <deploy-output.txt> [video-output.txt]"
fi

# ─────────────────────────────────────────────
# Parse a deploy-output.txt into variables
# ─────────────────────────────────────────────
parse_output() {
  local file="$1" prefix="$2"
  local ip uuid pubkey shortid sni
  ip=$(grep '^Server IP:' "$file" | awk '{print $NF}')
  uuid=$(grep '^UUID:' "$file" | awk '{print $NF}')
  pubkey=$(grep '^Reality Public Key:' "$file" | awk '{print $NF}')
  shortid=$(grep '^Short ID:' "$file" | awk '{print $NF}')
  sni=$(grep '^SNI:' "$file" | awk '{print $NF}')

  for var in ip uuid pubkey shortid sni; do
    eval "local val=\$$var"
    [[ -n "$val" ]] || error "Could not parse $var from $file"
  done

  eval "${prefix}_SERVER_IP='$ip'"
  eval "${prefix}_UUID='$uuid'"
  eval "${prefix}_PUBKEY='$pubkey'"
  eval "${prefix}_SHORTID='$shortid'"
  eval "${prefix}_SNI='$sni'"
}

if [[ "$MODE" == "single" ]]; then
  INPUT_FILE="$1"
  [[ -f "$INPUT_FILE" ]] || error "File not found: $INPUT_FILE"
  parse_output "$INPUT_FILE" NODE
  info "Parsed: server=$NODE_SERVER_IP"
  MODE_LABEL="Single-node setup"
  WORK_TARGET="Proxy"
  VIDEO_TARGET="Proxy"
  DEFAULT_TARGET="Proxy"
else
  WORK_FILE="$1"
  VIDEO_FILE="$2"
  [[ -f "$WORK_FILE" ]] || error "File not found: $WORK_FILE"
  [[ -f "$VIDEO_FILE" ]] || error "File not found: $VIDEO_FILE"
  parse_output "$WORK_FILE" WORK
  parse_output "$VIDEO_FILE" VIDEO
  info "Parsed: work=$WORK_SERVER_IP  video=$VIDEO_SERVER_IP"
  MODE_LABEL="Two-node setup: Work / Video"
  WORK_TARGET="Work"
  VIDEO_TARGET="Video"
  DEFAULT_TARGET="Work"
fi

OUTPUT="shadowrocket.conf"

# Shorthand for blackmatrix7 rule-set base URL
BM7="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket"

cat >"$OUTPUT" <<EOF_CONFIG
# Shadowrocket config — generated by punch/gen-shadowrocket-config.sh
# ${MODE_LABEL}

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, *.crashlytics.com, 127.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 224.0.0.0/4, fc00::/7, fe80::/10
dns-server = 223.5.5.5, 119.29.29.29
ipv6 = false
prefer-ipv4 = true
sniffing = true
icmp-auto-reply = true

[Proxy]
EOF_CONFIG

if [[ "$MODE" == "single" ]]; then
  cat >>"$OUTPUT" <<EOF_CONFIG
node-${NODE_SERVER_IP} = vless, ${NODE_SERVER_IP}, 443, method=none, password=${NODE_UUID}, proto=none, flow=xtls-rprx-vision, tls=true, sni=${NODE_SNI}, pbk=${NODE_PUBKEY}, sid=${NODE_SHORTID}, udp=1
Direct = direct

[Proxy Group]
Proxy = select,node-${NODE_SERVER_IP},Direct
EOF_CONFIG
else
  cat >>"$OUTPUT" <<EOF_CONFIG
work-${WORK_SERVER_IP} = vless, ${WORK_SERVER_IP}, 443, method=none, password=${WORK_UUID}, proto=none, flow=xtls-rprx-vision, tls=true, sni=${WORK_SNI}, pbk=${WORK_PUBKEY}, sid=${WORK_SHORTID}, udp=1
video-${VIDEO_SERVER_IP} = vless, ${VIDEO_SERVER_IP}, 443, method=none, password=${VIDEO_UUID}, proto=none, flow=xtls-rprx-vision, tls=true, sni=${VIDEO_SNI}, pbk=${VIDEO_PUBKEY}, sid=${VIDEO_SHORTID}, udp=1
Direct = direct

[Proxy Group]
Work = select,work-${WORK_SERVER_IP},video-${VIDEO_SERVER_IP},Direct
Video = select,video-${VIDEO_SERVER_IP},work-${WORK_SERVER_IP},Direct
EOF_CONFIG
fi

cat >>"$OUTPUT" <<EOF_CONFIG

[Rule]
# ─── Private & Local ───
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,169.254.0.0/16,DIRECT
IP-CIDR,224.0.0.0/4,DIRECT
DOMAIN-SUFFIX,local,DIRECT
DOMAIN-SUFFIX,lan,DIRECT

# ─── Ad Blocking ───
RULE-SET,${BM7}/Advertising/Advertising.list,REJECT

# ─── AI Services → ${WORK_TARGET} ───
RULE-SET,${BM7}/OpenAI/OpenAI.list,${WORK_TARGET}
DOMAIN-SUFFIX,anthropic.com,${WORK_TARGET}
DOMAIN-SUFFIX,claude.ai,${WORK_TARGET}
DOMAIN-SUFFIX,perplexity.ai,${WORK_TARGET}
DOMAIN-SUFFIX,gemini.google.com,${WORK_TARGET}

# ─── Dev Tools → ${WORK_TARGET} ───
RULE-SET,${BM7}/GitHub/GitHub.list,${WORK_TARGET}
DOMAIN-SUFFIX,ghcr.io,${WORK_TARGET}
DOMAIN-SUFFIX,raw.githubusercontent.com,${WORK_TARGET}
DOMAIN-SUFFIX,objects.githubusercontent.com,${WORK_TARGET}
DOMAIN-SUFFIX,golang.org,${WORK_TARGET}
DOMAIN-SUFFIX,go.dev,${WORK_TARGET}
DOMAIN-SUFFIX,proxy.golang.org,${WORK_TARGET}
DOMAIN-SUFFIX,sum.golang.org,${WORK_TARGET}
DOMAIN-SUFFIX,storage.googleapis.com,${WORK_TARGET}
DOMAIN-SUFFIX,registry.npmjs.org,${WORK_TARGET}
DOMAIN-SUFFIX,npmjs.com,${WORK_TARGET}
DOMAIN-SUFFIX,yarnpkg.com,${WORK_TARGET}
DOMAIN-SUFFIX,docker.io,${WORK_TARGET}
DOMAIN-SUFFIX,docker.com,${WORK_TARGET}
DOMAIN-SUFFIX,gcr.io,${WORK_TARGET}
DOMAIN-SUFFIX,k8s.io,${WORK_TARGET}
DOMAIN-SUFFIX,kubernetes.io,${WORK_TARGET}
DOMAIN-SUFFIX,registry.k8s.io,${WORK_TARGET}
DOMAIN-SUFFIX,dl.google.com,${WORK_TARGET}
DOMAIN-SUFFIX,dl-ssl.google.com,${WORK_TARGET}
DOMAIN-SUFFIX,crates.io,${WORK_TARGET}
DOMAIN-SUFFIX,static.crates.io,${WORK_TARGET}
DOMAIN-SUFFIX,rust-lang.org,${WORK_TARGET}
DOMAIN-SUFFIX,static.rust-lang.org,${WORK_TARGET}
DOMAIN-SUFFIX,pypi.org,${WORK_TARGET}
DOMAIN-SUFFIX,files.pythonhosted.org,${WORK_TARGET}
DOMAIN-SUFFIX,rubygems.org,${WORK_TARGET}
DOMAIN-SUFFIX,gradle.org,${WORK_TARGET}
DOMAIN-SUFFIX,repo.maven.apache.org,${WORK_TARGET}
DOMAIN-SUFFIX,plugins.gradle.org,${WORK_TARGET}
DOMAIN-SUFFIX,cocoapods.org,${WORK_TARGET}
DOMAIN-SUFFIX,cdn.cocoapods.org,${WORK_TARGET}
DOMAIN-SUFFIX,homebrew.sh,${WORK_TARGET}
DOMAIN-SUFFIX,formulae.brew.sh,${WORK_TARGET}
DOMAIN-SUFFIX,stackoverflow.com,${WORK_TARGET}
DOMAIN-SUFFIX,stackexchange.com,${WORK_TARGET}
DOMAIN-SUFFIX,askubuntu.com,${WORK_TARGET}
DOMAIN-SUFFIX,serverfault.com,${WORK_TARGET}
DOMAIN-SUFFIX,superuser.com,${WORK_TARGET}
DOMAIN-SUFFIX,medium.com,${WORK_TARGET}
DOMAIN-SUFFIX,dev.to,${WORK_TARGET}
DOMAIN-SUFFIX,hf.co,${WORK_TARGET}
DOMAIN-SUFFIX,huggingface.co,${WORK_TARGET}

# ─── Streaming & Media → ${VIDEO_TARGET} ───
RULE-SET,${BM7}/YouTube/YouTube.list,${VIDEO_TARGET}
RULE-SET,${BM7}/Netflix/Netflix.list,${VIDEO_TARGET}
DOMAIN-SUFFIX,spotify.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,spotifycdn.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,scdn.co,${VIDEO_TARGET}
DOMAIN-SUFFIX,twitch.tv,${VIDEO_TARGET}
DOMAIN-SUFFIX,ttvnw.net,${VIDEO_TARGET}
DOMAIN-SUFFIX,jtvnw.net,${VIDEO_TARGET}
DOMAIN-SUFFIX,disneyplus.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,disney-plus.net,${VIDEO_TARGET}
DOMAIN-SUFFIX,bamgrid.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,missav.ws,${VIDEO_TARGET}
DOMAIN-SUFFIX,recombee.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,pornhub.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,xhamster.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,faphouselive.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,91tanhua.net,${VIDEO_TARGET}
DOMAIN-SUFFIX,51cg1.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,dssott.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,hulu.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,hbo.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,hbomax.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,max.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,primevideo.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,aiv-cdn.net,${VIDEO_TARGET}
DOMAIN-SUFFIX,soundcloud.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,sndcdn.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,pandora.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,vimeo.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,vimeocdn.com,${VIDEO_TARGET}
DOMAIN-SUFFIX,dailymotion.com,${VIDEO_TARGET}

# ─── Google → ${WORK_TARGET} ───
RULE-SET,${BM7}/Google/Google.list,${WORK_TARGET}

# ─── Social Media → ${WORK_TARGET} ───
RULE-SET,${BM7}/Telegram/Telegram.list,${WORK_TARGET}
RULE-SET,${BM7}/Twitter/Twitter.list,${WORK_TARGET}
RULE-SET,${BM7}/Facebook/Facebook.list,${WORK_TARGET}
DOMAIN-SUFFIX,reddit.com,${WORK_TARGET}
DOMAIN-SUFFIX,redd.it,${WORK_TARGET}
DOMAIN-SUFFIX,redditmedia.com,${WORK_TARGET}
DOMAIN-SUFFIX,redditstatic.com,${WORK_TARGET}
DOMAIN-SUFFIX,discord.com,${WORK_TARGET}
DOMAIN-SUFFIX,discord.gg,${WORK_TARGET}
DOMAIN-SUFFIX,discordapp.com,${WORK_TARGET}
DOMAIN-SUFFIX,discordapp.net,${WORK_TARGET}
DOMAIN-SUFFIX,instagram.com,${WORK_TARGET}
DOMAIN-SUFFIX,cdninstagram.com,${WORK_TARGET}
DOMAIN-SUFFIX,linkedin.com,${WORK_TARGET}
DOMAIN-SUFFIX,licdn.com,${WORK_TARGET}
DOMAIN-SUFFIX,pinterest.com,${WORK_TARGET}
DOMAIN-SUFFIX,pinimg.com,${WORK_TARGET}
DOMAIN-SUFFIX,whatsapp.com,${WORK_TARGET}
DOMAIN-SUFFIX,whatsapp.net,${WORK_TARGET}
DOMAIN-SUFFIX,line.me,${WORK_TARGET}
DOMAIN-SUFFIX,line-scdn.net,${WORK_TARGET}
DOMAIN-SUFFIX,naver.jp,${WORK_TARGET}
DOMAIN-SUFFIX,signal.org,${WORK_TARGET}

# ─── News & Knowledge → ${WORK_TARGET} ───
DOMAIN-SUFFIX,wikipedia.org,${WORK_TARGET}
DOMAIN-SUFFIX,wikimedia.org,${WORK_TARGET}
DOMAIN-SUFFIX,wiktionary.org,${WORK_TARGET}
DOMAIN-SUFFIX,nytimes.com,${WORK_TARGET}
DOMAIN-SUFFIX,wsj.com,${WORK_TARGET}
DOMAIN-SUFFIX,bbc.com,${WORK_TARGET}
DOMAIN-SUFFIX,bbc.co.uk,${WORK_TARGET}
DOMAIN-SUFFIX,reuters.com,${WORK_TARGET}
DOMAIN-SUFFIX,theguardian.com,${WORK_TARGET}
DOMAIN-SUFFIX,apnews.com,${WORK_TARGET}
DOMAIN-SUFFIX,archive.org,${WORK_TARGET}

# ─── Cloud & CDN → ${WORK_TARGET} ───
DOMAIN-SUFFIX,cloudfront.net,${WORK_TARGET}
DOMAIN-SUFFIX,amazonaws.com,${WORK_TARGET}
DOMAIN-SUFFIX,s3.amazonaws.com,${WORK_TARGET}
DOMAIN-SUFFIX,heroku.com,${WORK_TARGET}
DOMAIN-SUFFIX,herokuapp.com,${WORK_TARGET}
DOMAIN-SUFFIX,vercel.app,${WORK_TARGET}
DOMAIN-SUFFIX,vercel.com,${WORK_TARGET}
DOMAIN-SUFFIX,netlify.app,${WORK_TARGET}
DOMAIN-SUFFIX,netlify.com,${WORK_TARGET}
DOMAIN-SUFFIX,pages.dev,${WORK_TARGET}
DOMAIN-SUFFIX,workers.dev,${WORK_TARGET}
DOMAIN-SUFFIX,r2.dev,${WORK_TARGET}
DOMAIN-SUFFIX,firebaseio.com,${WORK_TARGET}
DOMAIN-SUFFIX,firebase.google.com,${WORK_TARGET}
DOMAIN-SUFFIX,firebaseapp.com,${WORK_TARGET}
DOMAIN-SUFFIX,fly.dev,${WORK_TARGET}
DOMAIN-SUFFIX,fly.io,${WORK_TARGET}
DOMAIN-SUFFIX,railway.app,${WORK_TARGET}
DOMAIN-SUFFIX,render.com,${WORK_TARGET}
DOMAIN-SUFFIX,onrender.com,${WORK_TARGET}
DOMAIN-SUFFIX,supabase.co,${WORK_TARGET}
DOMAIN-SUFFIX,supabase.com,${WORK_TARGET}
DOMAIN-SUFFIX,deno.land,${WORK_TARGET}
DOMAIN-SUFFIX,deno.com,${WORK_TARGET}

# ─── Apple (accessible from China) ───
RULE-SET,${BM7}/Apple/Apple.list,DIRECT

# ─── Microsoft (accessible, except LinkedIn above) ───
RULE-SET,${BM7}/Microsoft/Microsoft.list,DIRECT

# ─── China Domestic Services ───
DOMAIN-SUFFIX,claude-code.club,DIRECT
DOMAIN-SUFFIX,baidu.com,DIRECT
DOMAIN-SUFFIX,doubao.com,DIRECT
DOMAIN-SUFFIX,tencent.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
DOMAIN-SUFFIX,taobao.com,DIRECT
DOMAIN-SUFFIX,jd.com,DIRECT
DOMAIN-SUFFIX,sina.com.cn,DIRECT
DOMAIN-SUFFIX,sohu.com,DIRECT
DOMAIN-SUFFIX,163.com,DIRECT
DOMAIN-SUFFIX,deepseek.com,DIRECT
DOMAIN-SUFFIX,qwen.ai,DIRECT
DOMAIN-SUFFIX,douban.com,DIRECT
DOMAIN-SUFFIX,minimax.io,DIRECT
DOMAIN-SUFFIX,minimaxi.com,DIRECT
DOMAIN-SUFFIX,zhipuai.cn,DIRECT
DOMAIN-SUFFIX,z.ai,DIRECT
DOMAIN-SUFFIX,tencencloud.com,DIRECT
DOMAIN-SUFFIX,aliyun.com,DIRECT

# ─── China Direct ───
GEOIP,CN,DIRECT

# ─── Default: everything else → ${DEFAULT_TARGET} ───
FINAL,${DEFAULT_TARGET}

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www\.)?g(oogle)?\.cn https://www.google.com 302
EOF_CONFIG

info "Generated $OUTPUT"
info "Import into Shadowrocket on iOS."
