#!/usr/bin/env bash
#
# punch/gen-shadowrocket-config.sh — Generate a Shadowrocket .conf file
# from two deploy-output.txt files (work, video).
#
# Usage:
#   ./gen-shadowrocket-config.sh <work-output.txt> <video-output.txt>
#
# Run locally on your Mac. Produces shadowrocket.conf in the current directory.
# Import into Shadowrocket on iOS via file sharing / AirDrop / iCloud.
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC}  $*"; }
error() {
  echo -e "${RED}[ERROR]${NC} $*"
  exit 1
}

[[ $# -eq 2 ]] || error "Usage: $0 <work-output.txt> <video-output.txt>"

WORK_FILE="$1"
VIDEO_FILE="$2"

for f in "$WORK_FILE" "$VIDEO_FILE"; do
  [[ -f "$f" ]] || error "File not found: $f"
done

# ─────────────────────────────────────────────
# Parse a deploy-output.txt into variables
# ─────────────────────────────────────────────
parse_output() {
  local file="$1" prefix="$2"
  local ip uuid pubkey shortid sni
  ip=$(grep '^Server IP:' "$file" | awk '{print $NF}')
  uuid=$(grep '^UUID:' "$file" | awk '{print $NF}')
  pubkey=$(grep '^Reality Public Key:' "$file" | awk '{print $NF}')
  shortid=$(grep '^Short ID:' "$file" | awk '{print $NF}')
  sni=$(grep '^SNI:' "$file" | awk '{print $NF}')

  for var in ip uuid pubkey shortid sni; do
    eval "local val=\$$var"
    [[ -n "$val" ]] || error "Could not parse $var from $file"
  done

  eval "${prefix}_IP='$ip'"
  eval "${prefix}_UUID='$uuid'"
  eval "${prefix}_PUBKEY='$pubkey'"
  eval "${prefix}_SHORTID='$shortid'"
  eval "${prefix}_SNI='$sni'"
}

parse_output "$WORK_FILE" WORK
parse_output "$VIDEO_FILE" VIDEO

info "Parsed: work=$WORK_IP  video=$VIDEO_IP"

OUTPUT="shadowrocket.conf"

# Shorthand for blackmatrix7 rule-set base URL
BM7="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket"

cat >"$OUTPUT" <<EOF
# Shadowrocket config — generated by punch/gen-shadowrocket-config.sh
# Two-node setup: Work / Video

[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, *.crashlytics.com, 127.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 224.0.0.0/4, fc00::/7, fe80::/10
dns-server = 223.5.5.5, 119.29.29.29
ipv6 = false
prefer-ipv4 = true
sniffing = true
icmp-auto-reply = true

[Proxy]
work-${WORK_IP} = vless, ${WORK_IP}, 443, method=none, password=${WORK_UUID}, proto=none, flow=xtls-rprx-vision, tls=true, sni=${WORK_SNI}, pbk=${WORK_PUBKEY}, sid=${WORK_SHORTID}, udp=1
video-${VIDEO_IP} = vless, ${VIDEO_IP}, 443, method=none, password=${VIDEO_UUID}, proto=none, flow=xtls-rprx-vision, tls=true, sni=${VIDEO_SNI}, pbk=${VIDEO_PUBKEY}, sid=${VIDEO_SHORTID}, udp=1
Direct = direct

[Proxy Group]
Work = select,work-${WORK_IP},video-${VIDEO_IP},Direct
Video = select,video-${VIDEO_IP},work-${WORK_IP},Direct

[Rule]
# ─── Private & Local ───
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
IP-CIDR,100.64.0.0/10,DIRECT
IP-CIDR,169.254.0.0/16,DIRECT
IP-CIDR,224.0.0.0/4,DIRECT
DOMAIN-SUFFIX,local,DIRECT
DOMAIN-SUFFIX,lan,DIRECT

# ─── Ad Blocking ───
RULE-SET,${BM7}/Advertising/Advertising.list,REJECT

# ─── AI Services → Work ───
RULE-SET,${BM7}/OpenAI/OpenAI.list,Work
DOMAIN-SUFFIX,anthropic.com,Work
DOMAIN-SUFFIX,claude.ai,Work
DOMAIN-SUFFIX,perplexity.ai,Work
DOMAIN-SUFFIX,gemini.google.com,Work

# ─── Dev Tools → Work ───
RULE-SET,${BM7}/GitHub/GitHub.list,Work
DOMAIN-SUFFIX,ghcr.io,Work
DOMAIN-SUFFIX,raw.githubusercontent.com,Work
DOMAIN-SUFFIX,objects.githubusercontent.com,Work
DOMAIN-SUFFIX,golang.org,Work
DOMAIN-SUFFIX,go.dev,Work
DOMAIN-SUFFIX,proxy.golang.org,Work
DOMAIN-SUFFIX,sum.golang.org,Work
DOMAIN-SUFFIX,storage.googleapis.com,Work
DOMAIN-SUFFIX,registry.npmjs.org,Work
DOMAIN-SUFFIX,npmjs.com,Work
DOMAIN-SUFFIX,yarnpkg.com,Work
DOMAIN-SUFFIX,docker.io,Work
DOMAIN-SUFFIX,docker.com,Work
DOMAIN-SUFFIX,gcr.io,Work
DOMAIN-SUFFIX,k8s.io,Work
DOMAIN-SUFFIX,kubernetes.io,Work
DOMAIN-SUFFIX,registry.k8s.io,Work
DOMAIN-SUFFIX,dl.google.com,Work
DOMAIN-SUFFIX,dl-ssl.google.com,Work
DOMAIN-SUFFIX,crates.io,Work
DOMAIN-SUFFIX,static.crates.io,Work
DOMAIN-SUFFIX,rust-lang.org,Work
DOMAIN-SUFFIX,static.rust-lang.org,Work
DOMAIN-SUFFIX,pypi.org,Work
DOMAIN-SUFFIX,files.pythonhosted.org,Work
DOMAIN-SUFFIX,rubygems.org,Work
DOMAIN-SUFFIX,gradle.org,Work
DOMAIN-SUFFIX,repo.maven.apache.org,Work
DOMAIN-SUFFIX,plugins.gradle.org,Work
DOMAIN-SUFFIX,cocoapods.org,Work
DOMAIN-SUFFIX,cdn.cocoapods.org,Work
DOMAIN-SUFFIX,homebrew.sh,Work
DOMAIN-SUFFIX,formulae.brew.sh,Work
DOMAIN-SUFFIX,stackoverflow.com,Work
DOMAIN-SUFFIX,stackexchange.com,Work
DOMAIN-SUFFIX,askubuntu.com,Work
DOMAIN-SUFFIX,serverfault.com,Work
DOMAIN-SUFFIX,superuser.com,Work
DOMAIN-SUFFIX,medium.com,Work
DOMAIN-SUFFIX,dev.to,Work
DOMAIN-SUFFIX,hf.co,Work
DOMAIN-SUFFIX,huggingface.co,Work

# ─── Streaming & Media → Video ───
RULE-SET,${BM7}/YouTube/YouTube.list,Video
RULE-SET,${BM7}/Netflix/Netflix.list,Video
DOMAIN-SUFFIX,spotify.com,Video
DOMAIN-SUFFIX,spotifycdn.com,Video
DOMAIN-SUFFIX,scdn.co,Video
DOMAIN-SUFFIX,twitch.tv,Video
DOMAIN-SUFFIX,ttvnw.net,Video
DOMAIN-SUFFIX,jtvnw.net,Video
DOMAIN-SUFFIX,disneyplus.com,Video
DOMAIN-SUFFIX,disney-plus.net,Video
DOMAIN-SUFFIX,bamgrid.com,Video
DOMAIN-SUFFIX,missav.ws,Video
DOMAIN-SUFFIX,recombee.com,Video
DOMAIN-SUFFIX,pornhub.com,Video
DOMAIN-SUFFIX,xhamster.com,Video
DOMAIN-SUFFIX,faphouselive.com,Video
DOMAIN-SUFFIX,91tanhua.net,Video
DOMAIN-SUFFIX,51cg1.com,Video
DOMAIN-SUFFIX,dssott.com,Video
DOMAIN-SUFFIX,hulu.com,Video
DOMAIN-SUFFIX,hbo.com,Video
DOMAIN-SUFFIX,hbomax.com,Video
DOMAIN-SUFFIX,max.com,Video
DOMAIN-SUFFIX,primevideo.com,Video
DOMAIN-SUFFIX,aiv-cdn.net,Video
DOMAIN-SUFFIX,soundcloud.com,Video
DOMAIN-SUFFIX,sndcdn.com,Video
DOMAIN-SUFFIX,pandora.com,Video
DOMAIN-SUFFIX,vimeo.com,Video
DOMAIN-SUFFIX,vimeocdn.com,Video
DOMAIN-SUFFIX,dailymotion.com,Video

# ─── Google → Work ───
RULE-SET,${BM7}/Google/Google.list,Work

# ─── Social Media → Work ───
RULE-SET,${BM7}/Telegram/Telegram.list,Work
RULE-SET,${BM7}/Twitter/Twitter.list,Work
RULE-SET,${BM7}/Facebook/Facebook.list,Work
DOMAIN-SUFFIX,reddit.com,Work
DOMAIN-SUFFIX,redd.it,Work
DOMAIN-SUFFIX,redditmedia.com,Work
DOMAIN-SUFFIX,redditstatic.com,Work
DOMAIN-SUFFIX,discord.com,Work
DOMAIN-SUFFIX,discord.gg,Work
DOMAIN-SUFFIX,discordapp.com,Work
DOMAIN-SUFFIX,discordapp.net,Work
DOMAIN-SUFFIX,instagram.com,Work
DOMAIN-SUFFIX,cdninstagram.com,Work
DOMAIN-SUFFIX,linkedin.com,Work
DOMAIN-SUFFIX,licdn.com,Work
DOMAIN-SUFFIX,pinterest.com,Work
DOMAIN-SUFFIX,pinimg.com,Work
DOMAIN-SUFFIX,whatsapp.com,Work
DOMAIN-SUFFIX,whatsapp.net,Work
DOMAIN-SUFFIX,line.me,Work
DOMAIN-SUFFIX,line-scdn.net,Work
DOMAIN-SUFFIX,naver.jp,Work
DOMAIN-SUFFIX,signal.org,Work

# ─── News & Knowledge → Work ───
DOMAIN-SUFFIX,wikipedia.org,Work
DOMAIN-SUFFIX,wikimedia.org,Work
DOMAIN-SUFFIX,wiktionary.org,Work
DOMAIN-SUFFIX,nytimes.com,Work
DOMAIN-SUFFIX,wsj.com,Work
DOMAIN-SUFFIX,bbc.com,Work
DOMAIN-SUFFIX,bbc.co.uk,Work
DOMAIN-SUFFIX,reuters.com,Work
DOMAIN-SUFFIX,theguardian.com,Work
DOMAIN-SUFFIX,apnews.com,Work
DOMAIN-SUFFIX,archive.org,Work

# ─── Cloud & CDN → Work ───
DOMAIN-SUFFIX,cloudfront.net,Work
DOMAIN-SUFFIX,amazonaws.com,Work
DOMAIN-SUFFIX,s3.amazonaws.com,Work
DOMAIN-SUFFIX,heroku.com,Work
DOMAIN-SUFFIX,herokuapp.com,Work
DOMAIN-SUFFIX,vercel.app,Work
DOMAIN-SUFFIX,vercel.com,Work
DOMAIN-SUFFIX,netlify.app,Work
DOMAIN-SUFFIX,netlify.com,Work
DOMAIN-SUFFIX,pages.dev,Work
DOMAIN-SUFFIX,workers.dev,Work
DOMAIN-SUFFIX,r2.dev,Work
DOMAIN-SUFFIX,firebaseio.com,Work
DOMAIN-SUFFIX,firebase.google.com,Work
DOMAIN-SUFFIX,firebaseapp.com,Work
DOMAIN-SUFFIX,fly.dev,Work
DOMAIN-SUFFIX,fly.io,Work
DOMAIN-SUFFIX,railway.app,Work
DOMAIN-SUFFIX,render.com,Work
DOMAIN-SUFFIX,onrender.com,Work
DOMAIN-SUFFIX,supabase.co,Work
DOMAIN-SUFFIX,supabase.com,Work
DOMAIN-SUFFIX,deno.land,Work
DOMAIN-SUFFIX,deno.com,Work

# ─── Apple (accessible from China) ───
RULE-SET,${BM7}/Apple/Apple.list,DIRECT

# ─── Microsoft (accessible, except LinkedIn above) ───
RULE-SET,${BM7}/Microsoft/Microsoft.list,DIRECT

# ─── China Domestic Services ───
DOMAIN-SUFFIX,claude-code.club,DIRECT
DOMAIN-SUFFIX,baidu.com,DIRECT
DOMAIN-SUFFIX,doubao.com,DIRECT
DOMAIN-SUFFIX,tencent.com,DIRECT
DOMAIN-SUFFIX,qq.com,DIRECT
DOMAIN-SUFFIX,taobao.com,DIRECT
DOMAIN-SUFFIX,jd.com,DIRECT
DOMAIN-SUFFIX,sina.com.cn,DIRECT
DOMAIN-SUFFIX,sohu.com,DIRECT
DOMAIN-SUFFIX,163.com,DIRECT
DOMAIN-SUFFIX,deepseek.com,DIRECT
DOMAIN-SUFFIX,qwen.ai,DIRECT
DOMAIN-SUFFIX,douban.com,DIRECT
DOMAIN-SUFFIX,minimax.io,DIRECT
DOMAIN-SUFFIX,minimaxi.com,DIRECT
DOMAIN-SUFFIX,zhipuai.cn,DIRECT
DOMAIN-SUFFIX,z.ai,DIRECT
DOMAIN-SUFFIX,tencencloud.com,DIRECT
DOMAIN-SUFFIX,aliyun.com,DIRECT

# ─── China Direct ───
GEOIP,CN,DIRECT

# ─── Default: everything else → Work ───
FINAL,Work

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www\.)?g(oogle)?\.cn https://www.google.com 302
EOF

info "Generated $OUTPUT"
info "Import into Shadowrocket on iOS."
