#!/usr/bin/env bash
#
# punch/gen-clash.sh — Generate a combined Clash Verge (mihomo) config
# from three deploy-output.txt files (dev, work, video).
#
# Usage:
#   ./gen-clash.sh <dev-output.txt> <work-output.txt> <video-output.txt>
#
# Run locally on your Mac. Produces clash.yaml in the current directory.
#
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

[[ $# -eq 3 ]] || error "Usage: $0 <dev-output.txt> <work-output.txt> <video-output.txt>"

DEV_FILE="$1"
WORK_FILE="$2"
VIDEO_FILE="$3"

for f in "$DEV_FILE" "$WORK_FILE" "$VIDEO_FILE"; do
  [[ -f "$f" ]] || error "File not found: $f"
done

# ─────────────────────────────────────────────
# Parse a deploy-output.txt into variables
# ─────────────────────────────────────────────
parse_output() {
  local file="$1" prefix="$2"
  local ip uuid pubkey shortid sni
  ip=$(grep '^Server IP:' "$file" | awk '{print $NF}')
  uuid=$(grep '^UUID:' "$file" | awk '{print $NF}')
  pubkey=$(grep '^Reality Public Key:' "$file" | awk '{print $NF}')
  shortid=$(grep '^Short ID:' "$file" | awk '{print $NF}')
  sni=$(grep '^SNI:' "$file" | awk '{print $NF}')

  for var in ip uuid pubkey shortid sni; do
    eval "local val=\$$var"
    [[ -n "$val" ]] || error "Could not parse $var from $file"
  done

  eval "${prefix}_IP='$ip'"
  eval "${prefix}_UUID='$uuid'"
  eval "${prefix}_PUBKEY='$pubkey'"
  eval "${prefix}_SHORTID='$shortid'"
  eval "${prefix}_SNI='$sni'"
}

parse_output "$DEV_FILE" DEV
parse_output "$WORK_FILE" WORK
parse_output "$VIDEO_FILE" VIDEO

info "Parsed: dev=$DEV_IP  work=$WORK_IP  video=$VIDEO_IP"

OUTPUT="clash.yaml"

# ─────────────────────────────────────────────
# Global settings + DNS
# ─────────────────────────────────────────────
cat >"$OUTPUT" <<'HEAD'
# Clash Verge (mihomo) config — generated by punch/gen-clash.sh
# Three-node setup: Dev / Work / Video

mixed-port: 7897
allow-lan: false
mode: rule
log-level: warning
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
geo-auto-update: true
geo-update-interval: 24

dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.localhost"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "captive.apple.com"
    - "connectivitycheck.gstatic.com"
    - "connectivitycheck.platform.hicloud.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - "tls://8.8.8.8:853"
    - "tls://1.1.1.1:853"
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

HEAD

# ─────────────────────────────────────────────
# Proxies
# ─────────────────────────────────────────────
cat >>"$OUTPUT" <<EOF
proxies:
  - name: dev-${DEV_IP}
    type: vless
    server: ${DEV_IP}
    port: 443
    uuid: ${DEV_UUID}
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: ${DEV_SNI}
    client-fingerprint: chrome
    reality-opts:
      public-key: ${DEV_PUBKEY}
      short-id: ${DEV_SHORTID}

  - name: work-${WORK_IP}
    type: vless
    server: ${WORK_IP}
    port: 443
    uuid: ${WORK_UUID}
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: ${WORK_SNI}
    client-fingerprint: chrome
    reality-opts:
      public-key: ${WORK_PUBKEY}
      short-id: ${WORK_SHORTID}

  - name: video-${VIDEO_IP}
    type: vless
    server: ${VIDEO_IP}
    port: 443
    uuid: ${VIDEO_UUID}
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: ${VIDEO_SNI}
    client-fingerprint: chrome
    reality-opts:
      public-key: ${VIDEO_PUBKEY}
      short-id: ${VIDEO_SHORTID}

EOF

# ─────────────────────────────────────────────
# Proxy groups
# ─────────────────────────────────────────────
cat >>"$OUTPUT" <<EOF
proxy-groups:
  - name: Dev
    type: select
    proxies:
      - dev-${DEV_IP}
      - work-${WORK_IP}
      - video-${VIDEO_IP}
      - DIRECT

  - name: Work
    type: select
    proxies:
      - work-${WORK_IP}
      - dev-${DEV_IP}
      - video-${VIDEO_IP}
      - DIRECT

  - name: Video
    type: select
    proxies:
      - video-${VIDEO_IP}
      - work-${WORK_IP}
      - dev-${DEV_IP}
      - DIRECT

EOF

# ─────────────────────────────────────────────
# Rules
# ─────────────────────────────────────────────
cat >>"$OUTPUT" <<'RULES'
rules:
  # ─── Private & Local ───
  - GEOIP,private,DIRECT,no-resolve
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT

  # ─── Ad Blocking ───
  - GEOSITE,category-ads-all,REJECT

  # ─── AI Services → Dev ───
  - GEOSITE,openai,Dev
  - DOMAIN-SUFFIX,anthropic.com,Dev
  - DOMAIN-SUFFIX,claude.ai,Dev
  - DOMAIN-SUFFIX,perplexity.ai,Dev
  - DOMAIN-SUFFIX,gemini.google.com,Dev

  # ─── Dev Tools → Dev ───
  - GEOSITE,github,Dev
  - DOMAIN-SUFFIX,ghcr.io,Dev
  - DOMAIN-SUFFIX,raw.githubusercontent.com,Dev
  - DOMAIN-SUFFIX,objects.githubusercontent.com,Dev
  - DOMAIN-SUFFIX,golang.org,Dev
  - DOMAIN-SUFFIX,go.dev,Dev
  - DOMAIN-SUFFIX,proxy.golang.org,Dev
  - DOMAIN-SUFFIX,sum.golang.org,Dev
  - DOMAIN-SUFFIX,storage.googleapis.com,Dev
  - DOMAIN-SUFFIX,registry.npmjs.org,Dev
  - DOMAIN-SUFFIX,npmjs.com,Dev
  - DOMAIN-SUFFIX,yarnpkg.com,Dev
  - DOMAIN-SUFFIX,docker.io,Dev
  - DOMAIN-SUFFIX,docker.com,Dev
  - DOMAIN-SUFFIX,gcr.io,Dev
  - DOMAIN-SUFFIX,k8s.io,Dev
  - DOMAIN-SUFFIX,kubernetes.io,Dev
  - DOMAIN-SUFFIX,registry.k8s.io,Dev
  - DOMAIN-SUFFIX,dl.google.com,Dev
  - DOMAIN-SUFFIX,dl-ssl.google.com,Dev
  - DOMAIN-SUFFIX,crates.io,Dev
  - DOMAIN-SUFFIX,static.crates.io,Dev
  - DOMAIN-SUFFIX,rust-lang.org,Dev
  - DOMAIN-SUFFIX,static.rust-lang.org,Dev
  - DOMAIN-SUFFIX,pypi.org,Dev
  - DOMAIN-SUFFIX,files.pythonhosted.org,Dev
  - DOMAIN-SUFFIX,rubygems.org,Dev
  - DOMAIN-SUFFIX,gradle.org,Dev
  - DOMAIN-SUFFIX,repo.maven.apache.org,Dev
  - DOMAIN-SUFFIX,plugins.gradle.org,Dev
  - DOMAIN-SUFFIX,cocoapods.org,Dev
  - DOMAIN-SUFFIX,cdn.cocoapods.org,Dev
  - DOMAIN-SUFFIX,homebrew.sh,Dev
  - DOMAIN-SUFFIX,formulae.brew.sh,Dev
  - DOMAIN-SUFFIX,stackoverflow.com,Dev
  - DOMAIN-SUFFIX,stackexchange.com,Dev
  - DOMAIN-SUFFIX,askubuntu.com,Dev
  - DOMAIN-SUFFIX,serverfault.com,Dev
  - DOMAIN-SUFFIX,superuser.com,Dev
  - DOMAIN-SUFFIX,medium.com,Dev
  - DOMAIN-SUFFIX,dev.to,Dev
  - DOMAIN-SUFFIX,hf.co,Dev
  - DOMAIN-SUFFIX,huggingface.co,Dev

  # ─── Streaming & Media → Video ───
  - GEOSITE,youtube,Video
  - GEOSITE,netflix,Video
  - DOMAIN-SUFFIX,spotify.com,Video
  - DOMAIN-SUFFIX,spotifycdn.com,Video
  - DOMAIN-SUFFIX,scdn.co,Video
  - DOMAIN-SUFFIX,twitch.tv,Video
  - DOMAIN-SUFFIX,ttvnw.net,Video
  - DOMAIN-SUFFIX,jtvnw.net,Video
  - DOMAIN-SUFFIX,disneyplus.com,Video
  - DOMAIN-SUFFIX,disney-plus.net,Video
  - DOMAIN-SUFFIX,bamgrid.com,Video
  - DOMAIN-SUFFIX,dssott.com,Video
  - DOMAIN-SUFFIX,hulu.com,Video
  - DOMAIN-SUFFIX,hbo.com,Video
  - DOMAIN-SUFFIX,hbomax.com,Video
  - DOMAIN-SUFFIX,max.com,Video
  - DOMAIN-SUFFIX,primevideo.com,Video
  - DOMAIN-SUFFIX,aiv-cdn.net,Video
  - DOMAIN-SUFFIX,soundcloud.com,Video
  - DOMAIN-SUFFIX,sndcdn.com,Video
  - DOMAIN-SUFFIX,pandora.com,Video
  - DOMAIN-SUFFIX,vimeo.com,Video
  - DOMAIN-SUFFIX,vimeocdn.com,Video
  - DOMAIN-SUFFIX,dailymotion.com,Video

  # ─── Google → Work ───
  - GEOSITE,google,Work

  # ─── Social Media → Work ───
  - GEOSITE,twitter,Work
  - GEOSITE,facebook,Work
  - GEOSITE,telegram,Work
  - DOMAIN-SUFFIX,reddit.com,Work
  - DOMAIN-SUFFIX,redd.it,Work
  - DOMAIN-SUFFIX,redditmedia.com,Work
  - DOMAIN-SUFFIX,redditstatic.com,Work
  - DOMAIN-SUFFIX,discord.com,Work
  - DOMAIN-SUFFIX,discord.gg,Work
  - DOMAIN-SUFFIX,discordapp.com,Work
  - DOMAIN-SUFFIX,discordapp.net,Work
  - DOMAIN-SUFFIX,instagram.com,Work
  - DOMAIN-SUFFIX,cdninstagram.com,Work
  - DOMAIN-SUFFIX,linkedin.com,Work
  - DOMAIN-SUFFIX,licdn.com,Work
  - DOMAIN-SUFFIX,pinterest.com,Work
  - DOMAIN-SUFFIX,pinimg.com,Work
  - DOMAIN-SUFFIX,whatsapp.com,Work
  - DOMAIN-SUFFIX,whatsapp.net,Work
  - DOMAIN-SUFFIX,line.me,Work
  - DOMAIN-SUFFIX,line-scdn.net,Work
  - DOMAIN-SUFFIX,naver.jp,Work
  - DOMAIN-SUFFIX,signal.org,Work

  # ─── News & Knowledge → Work ───
  - GEOSITE,wikipedia,Work
  - DOMAIN-SUFFIX,wikimedia.org,Work
  - DOMAIN-SUFFIX,wiktionary.org,Work
  - DOMAIN-SUFFIX,nytimes.com,Work
  - DOMAIN-SUFFIX,wsj.com,Work
  - DOMAIN-SUFFIX,bbc.com,Work
  - DOMAIN-SUFFIX,bbc.co.uk,Work
  - DOMAIN-SUFFIX,reuters.com,Work
  - DOMAIN-SUFFIX,theguardian.com,Work
  - DOMAIN-SUFFIX,apnews.com,Work
  - DOMAIN-SUFFIX,archive.org,Work

  # ─── Cloud & CDN → Dev ───
  - DOMAIN-SUFFIX,cloudfront.net,Dev
  - DOMAIN-SUFFIX,amazonaws.com,Dev
  - DOMAIN-SUFFIX,s3.amazonaws.com,Dev
  - DOMAIN-SUFFIX,heroku.com,Dev
  - DOMAIN-SUFFIX,herokuapp.com,Dev
  - DOMAIN-SUFFIX,vercel.app,Dev
  - DOMAIN-SUFFIX,vercel.com,Dev
  - DOMAIN-SUFFIX,netlify.app,Dev
  - DOMAIN-SUFFIX,netlify.com,Dev
  - DOMAIN-SUFFIX,pages.dev,Dev
  - DOMAIN-SUFFIX,workers.dev,Dev
  - DOMAIN-SUFFIX,r2.dev,Dev
  - DOMAIN-SUFFIX,firebaseio.com,Dev
  - DOMAIN-SUFFIX,firebase.google.com,Dev
  - DOMAIN-SUFFIX,firebaseapp.com,Dev
  - DOMAIN-SUFFIX,fly.dev,Dev
  - DOMAIN-SUFFIX,fly.io,Dev
  - DOMAIN-SUFFIX,railway.app,Dev
  - DOMAIN-SUFFIX,render.com,Dev
  - DOMAIN-SUFFIX,onrender.com,Dev
  - DOMAIN-SUFFIX,supabase.co,Dev
  - DOMAIN-SUFFIX,supabase.com,Dev
  - DOMAIN-SUFFIX,deno.land,Dev
  - DOMAIN-SUFFIX,deno.com,Dev

  # ─── Apple (accessible from China) ───
  - GEOSITE,apple,DIRECT

  # ─── Microsoft (accessible, except LinkedIn above) ───
  - GEOSITE,microsoft,DIRECT

  # ─── China Domestic Services ───
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,doubao.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,sina.com.cn,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,deepseek.com,DIRECT
  - DOMAIN-SUFFIX,qwen.ai,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT

  # ─── China Direct ───
  - GEOSITE,cn,DIRECT
  - GEOIP,CN,DIRECT

  # ─── Default: everything else → Work ───
  - MATCH,Work
RULES

info "Generated $OUTPUT"
info "Import into Clash Verge on macOS."
